SKILL_WEIGHTS = {
    "Python": 5,
    "Machine Learning": 5,
    "Artificial Intelligence": 5,
    "FastAPI": 4,
    "SQL": 4,
    "TensorFlow": 4,
    "PyTorch": 4,
    "Docker": 3,
    "AWS": 3,
    "Git": 2,
    "GitHub": 2,
    "Pandas": 3,
    "NumPy": 3,
    "Scikit-learn": 4,
    "NLP": 4,
    "Java": 3,
    "C++": 3,
    "Azure": 3,
    "Linux": 3,
}